### ISSUE TITLE
Settings not saving with Object cache / Memcached

### ISSUE THREAD

**Issue by mennobouma** [froger-me/wp-remote-users-sync#12]
[From Wordpress.org]

Hi Alexandre,

First of all, thanks for your great support :).

I’m running on WPMU DEV Hosting (https://premium.wpmudev.org/hosting/) and i’m trying to save the settings of the plugin. But after saving the settings they are back to the previous version and after about 30 minutes the settings appear to be changed to my latest input. So there is some sort of lag.

I think that after a cache flush the settings are good but it’s not very handy :). I run your plugin on other hosting and here the issue doesn’t happen.

It’s only happening in your plugin, i can save settings in other plugins.

I did a test with only your plugin enabled and with the Twentytwenty theme and the issue is still there.

Any idea how to solve this?

Thanks!
Menno

**Comment by froger-me** [comment]
Hi @mennobouma !

Glad to see you here - the WordPress plugin repo doesn't allow dev code, and the forum guidelines are very strict regarding what can be discussed, and the moderation team is rather unforgiving (see how it went down [here](https://wordpress.org/support/topic/settings-not-saving-54/)).

My account is in fact under active moderation, each message has to be manually approved by a moderator until they decide otherwise, without disclosed expiration... So I would rather be careful to and not have my account closed.
Below is what I get each time I post something there:

<img width="552" alt="Screen Shot 2020-09-07 at 8 18 10 PM" src="https://user-images.githubusercontent.com/3622456/92827422-6af97000-f404-11ea-9482-d74c6adeb7ba.png">

You can find the [v1.2.7-dev version here](https://github.com/froger-me/wp-remote-users-sync/releases/tag/v1.2.7-dev) - use at your own risks!

Changelog so far:
* Fix settings cache issues - for real...
* Fix log output
* Fix permalinks patterns
* Add `wprus_fire_action_timeout` filter hook

**Comment by mennobouma** [comment]
Hello Alexandre,

I understand the strict guidelines of the Wordpress forum. Glad we can chat without worries here :).

I tested the 1.2.7. and the cache issues are solved now! :D It's now saving the plugin settings directly.

Thanks again for your great support, i really appreciate it :).

Menno
