### ISSUE TITLE
Subsite user not syncing on main site /network in Multisite

### ISSUE THREAD

**Issue by Hsherazch762** [froger-me/wp-remote-users-sync#33]
Hi there,
Hope you are doing well i need to discuss and issue and hope so you will give me a solution for it.
I have setup Multisite on server
Main site: https://aletere.com/
sub-site: https://sub.aletere.com/

I just installed your plugin but when i added a user on sub-site i can’ see it on the main site users list. Please give me a solution.
Also tell me should i need to install a plugin also on the sub-site.Just asking as i also installed it on subdomain site.

**Comment by ptrsmk** [comment]
Did you Network Activate the plugin or activate it separately on each site?

**Comment by qstudio** [comment]
this plugin - if network activated - reads from the wrong tables for it's own settings, like logs and nonces, so you need to fork it and use base_prefix - instead of $wpdb->prefix - also for user and usermeta tables.

A fix could be made to wrap the prefix selection in some wp API like is_plugin_active_for_network

**Comment by qstudio** [comment]
This patch tries to address multisite issues - https://github.com/TotalAccessHealth/wp-remote-users-sync

**Comment by froger-me** [comment]
fixed in 2.0
