### ISSUE TITLE
Connection over https doesent work

### ISSUE THREAD

**Issue by 0ofland** [froger-me/wp-remote-users-sync#42]
I tried to set up a sync between my two WordPress sites and I had some trouble getting everything set up. I used the exact address listed in the "WordPress Address (URL)" in the setting, but it didn't seem to work the same with localhost I tried everything from setting up new security keys to adding the "/" at the end of the address nothing seemed to work, but then I tied the address with http and to my surprise the connection was successful. Not only that, but I did not read anything in any documentation that SSL wasn't supported? Both sites have a valid SSL certificate, and again I used the exact same address as in "WordPress Address (URL)". 

I mean, if it works, but I'm a bit concerned about security without SSL. **To my understanding, the security keys are used to de- and encrypt any data sent, right?** If this is the case, this shouldn't be a problem.

**Comment by buck8ochickn** [comment]
@0ofland under Settings>General> Wordpress address url. you have most likely never changed the default address so it is still using http:// and not https:// so in the log when you see it failing, "action is not activated on http<<<<<<< "it is because the server is giving the wrong official url name even though the connection works it will not update the wrong site name.

@froger-me please close
