### ISSUE TITLE
Pings not working as intended

### ISSUE THREAD

**Issue by TheHandOfKing** [froger-me/wp-remote-users-sync#8]
Pings (all of them) from site A to site B work fine (both), but the issue occurs when a ping is coming vice versa, The error message i get is this: 

 Success - Access granted - http://sitename
Warning - Ping received for deactivated action "Create" from http://sitename

Now the funny thing is that both sites are https, if you know a solution to this problem i'd be thankful

EDIT: I was tinkering a bit and found out that the error is indeed in the protocol, site with http states that it is https, but your plugin recodnizes it as a http

**Comment by froger-me** [comment]
Hi @TheHandOfKing 
Sorry for the late reply. This is a common issue as shown by other topics opened on wordpress.org, because it seems some https plugins (including cloudflare plugin) do not respect the value home_url saved in the database. It is a shame, but it really is important to make sure the URL matches exactly with what is saved in the wp_options table across the board.
Glad you found a solution.
